# Generated by Django 4.2.3 on 2023-07-24 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_rename_tasks_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
